### ISSUE TITLE
Unable to connect to server?

### ISSUE THREAD

**Issue by TSEG6** [LittlestCube/Zelda64Recomp#6]
![image](https://github.com/user-attachments/assets/4b33e1e3-7a64-4022-b684-9d340dc1f245)

Not sure if I messed it up but no matter what I do I always get this error unless if I change AP server to false
I also tried changing the IP but again same issue.

Not sure what to do now.

Thanks

**Comment by LittleCube-hax** [comment]
Where is your AP server set up? Is it on archipelago.gg or is it running locally?

**Comment by TSEG6** [comment]
I forgot to mention this but I managed to get it working, sorry about that.

**Comment by LittleCube-hax** [comment]
Haha no worries, glad it worked out for you.
